@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
class Fibanacci {
 - memo : Map<Integer, Long>
 +main(args : String[]) : void
 +fibonacciDP(n : int) : long
 +fibonacciRecursive(n : int) : long
 +fibanacciIterative(n : int) ; long
}
Fibanacci <|-- java.util.Map
Fibanacci <|-- java.util.HashMap

@enduml
